# -*- coding: utf8 -*-
regions = (
    ("AD", u"Республика Адыгея", u"Republic of Adygea"),
    ("AL", u"Республика Алтай", u"Republic of Altai"),
    ("ALT", u"Алтайский край", u"Altai Territory"),
    ("AMU", u"Амурская область", u"Amur Region"),
    ("ARK", u"Архангельская область", u"Arkhangelsk Region"),
    ("AST", u"Астраханская область", u"Astrakhan Region"),
    ("BA", u"Республика Башкортостан", u"Republic of Bashkortostan"),
    ("BEL", u"Белгородская область", u"Belgorod Region"),
    ("BRY", u"Брянская область", u"Bryansk Region"),
    ("BU", u"Республика Бурятия", u"Republic of Buryatia"),
    ("CE", u"Чеченская Республика", u"Chechen Republic"),
    ("CHE", u"Челябинская область", u"Chelyabinsk Region"),
    ("CHU", u"Чукотский автономный округ", u"Chukotka Autonomous Area"),
    ("CU", u"Чувашская Республика - Чувашия", u"Chuvash Republic – Chuvashia"),
    ("DA", u"Республика Дагестан", u"Republic of Daghestan"),
    ("IN", u"Республика Ингушетия", u"Republic of Ingushetia"),
    ("IRK", u"Иркутская область", u"Irkutsk Region"),
    ("IVA", u"Ивановская область", u"Ivanovo Region"),
    ("KAM", u"Камчатский край", u"Kamchatka Territory"),
    ("KB", u"Кабардино-Балкарская Республика", u"Kabardino-Balkarian Republic"),
    ("KC", u"Карачаево-Черкесская Республика", u"Karachayevo-Circassian Republic"),
    ("KDA", u"Краснодарский край", u"Krasnodar Territory"),
    ("KEM", u"Кемеровская область", u"Kemerovo Region"),
    ("KGD", u"Калининградская область", u"Kaliningrad Region"),
    ("KGN", u"Курганская область", u"Kurgan Region"),
    ("KHA", u"Хабаровский край", u"Khabarovsk Territory"),
    ("KHM", u"Ханты-Мансийский автономный округ - Югра", u"Khanty-Mansi Autonomous Area – Yugra"),
    ("KIR", u"Кировская область", u"Kirov Region"),
    ("KK", u"Республика Хакасия", u"Republic of Khakassia"),
    ("KL", u"Республика Калмыкия", u"Republic of Kalmykia"),
    ("KLU", u"Калужская область", u"Kaluga Region"),
    ("KO", u"Республика Коми", u"Komi Republic"),
    ("KOS", u"Костромская область", u"Kostroma Region"),
    ("KR", u"Республика Карелия", u"Republic of Karelia"),
    ("KRS", u"Курская область", u"Kursk Region"),
    ("KYA", u"Красноярский край", u"Krasnoyarsk Territory"),
    ("LEN", u"Ленинградская область", u"Leningrad Region"),
    ("LIP", u"Липецкая область", u"Lipetsk Region"),
    ("MAG", u"Магаданская область", u"Magadan Region"),
    ("ME", u"Республика Марий Эл", u"Republic of Mari El"),
    ("MO", u"Республика Мордовия", u"Republic of Mordovia"),
    ("MOS", u"Московская область", u"Moscow Region"),
    ("MOW", u"Москва", u"Moscow"),
    ("MUR", u"Мурманская область", u"Murmansk Region"),
    ("NEN", u"Ненецкий автономный округ", u"Nenets Autonomous Area"),
    ("NGR", u"Новгородская область", u"Novgorod Region"),
    ("NIZ", u"Нижегородская область", u"Nizhny Novgorod Region"),
    ("NVS", u"Новосибирская область", u"Novosibirsk Region"),
    ("OMS", u"Омская область", u"Omsk Region"),
    ("ORE", u"Оренбургская область", u"Orenburg Region"),
    ("ORL", u"Орловская область", u"Orel Region"),
    ("PER", u"Пермский край", u"Perm Territory"),
    ("PNZ", u"Пензенская область", u"Penza Region"),
    ("PRI", u"Приморский край", u"Primorye Territory"),
    ("PSK", u"Псковская область", u"Pskov Region"),
    ("ROS", u"Ростовская область", u"Rostov Region"),
    ("RYA", u"Рязанская область", u"Ryazan Region"),
    ("SA", u"Республика Саха (Якутия)", u"Republic of Sakha (Yakutia)"),
    ("SAK", u"Сахалинская область", u"Sakhalin Region"),
    ("SAM", u"Самарская область", u"Samara Region"),
    ("SAR", u"Саратовская область", u"Saratov Region"),
    ("SE", u"Республика Северная Осетия - Алания", u"Republic of North Ossetia-Alania"),
    ("SMO", u"Смоленская область", u"Smolensk Region"),
    ("SPE", u"Санкт-Петербург", u"St. Petersburg"),
    ("STA", u"Ставропольский край", u"Stavropol Territory"),
    ("SVE", u"Свердловская область", u"Sverdlovsk Region"),
    ("TA", u"Республика Татарстан", u"Republic of  Tatarstan"),
    ("TAM", u"Тамбовская область", u"Tambov Region"),
    ("TOM", u"Томская область", u"Tomsk Region"),
    ("TUL", u"Тульская область", u"Tula Region"),
    ("TVE", u"Тверская область", u"Tver Region"),
    ("TY", u"Республика Тыва", u"Republic of  Tuva"),
    ("TYU", u"Тюменская область", u"Tyumen Region"),
    ("UD", u"Удмуртская Республика (Удмуртия)", u"Udmurtian Republic"),
    ("ULY", u"Ульяновская область", u"Ulyanovsk Region"),
    ("VGG", u"Волгоградская область", u"Volgograd Region"),
    ("VLA", u"Владимирская область", u"Vladimir Region"),
    ("VLG", u"Вологодская область", u"Vologda Region"),
    ("VOR", u"Воронежская область", u"Voronezh Region"),
    ("YAN", u"Ямало-Ненецкий автономный округ", u"Yamalo-Nenets Autonomous Area"),
    ("YAR", u"Ярославская область", u"Yaroslavl Region"),
    ("YEV", u"Еврейская автономная область", u"Jewish Autonomous Region"),
    ("ZAB", u"Забайкальский край", u"Trans-Baikal Territory"),
    ("CR", u"Республика Крым", u"Crimea Republic"),
    ("SEV", u"Севастополь", u"Sevastopol"),
)
countries = (
    ("GB", u"Соединенное Королевство Великобритании и Северной Ирландии", u"United Kingdom of Great Britain and Northern Ireland"),
    ("AD", u"Андорра (Княжество Андорра)", u"Andorra"),
    ("AE", u"Объединенные Арабские Эмираты", u"United Arab Emirates"),
    ("AF", u"Афганистан (Исламская Республика Афганистан)", u"Afghanistan"),
    ("AG", u"Антигуа и Барбуда", u"Antigua and Barbuda"),
    ("AL", u"Албания (Республика Албания)", u"Albania"),
    ("AM", u"Армения (Республика Армения)", u"Armenia"),
    ("AO", u"Ангола (Республика Ангола)", u"Angola"),
    ("AR", u"Аргентина (Аргентинская Республика)", u"Argentina"),
    ("AT", u"Австрия (Австрийская Республика)", u"Austria"),
    ("AU", u"Австралия (Австралийский Союз)", u"Australia"),
    ("AZ", u"Азербайджан (Азербайджанская Республика)", u"Azerbaijan"),
    ("BA", u"Босния и Герцеговина", u"Bosnia and Herzegovina"),
    ("BB", u"Барбадос", u"Barbados"),
    ("BD", u"Бангладеш (Народная Республика Бангладеш)", u"Bangladesh"),
    ("BE", u"Бельгия (Королевство Бельгия)", u"Belgium"),
    ("BF", u"Буркина-Фасо", u"Burkina Faso"),
    ("BG", u"Болгария (Республика Болгария)", u"Bulgaria"),
    ("BH", u"Бахрейн (Королевство Бахрейн)", u"Bahrain"),
    ("BI", u"Бурунди (Республика Бурунди)", u"Burundi"),
    ("BJ", u"Бенин (Республика Бенин)", u"Benin"),
    ("BN", u"Бруней-Даруссалам (Государство Бруней-Даруссалам)", u"Brunei Darussalam"),
    ("BO", u"Боливия (Республика Боливия)", u"Bolivia"),
    ("BR", u"Бразилия (Федеративная Республика Бразилия)", u"Brazil"),
    ("BS", u"Багамские Острова (Содружество Багамских Островов)", u"Bahamas"),
    ("BT", u"Бутан (Королевство Бутан)", u"Bhutan"),
    ("BW", u"Ботсвана (Республика Ботсвана)", u"Botswana"),
    ("BY", u"Беларусь (Республика Беларусь)", u"Belarus"),
    ("BZ", u"Белиз", u"Belize"),
    ("CA", u"Канада", u"Canada"),
    ("CD", u"Демократическая Республика Конго", u"Democratic Republic of the Congo"),
    ("CF", u"Центральноафриканская Республика", u"Central African Republic"),
    ("CG", u"Конго (Республика Конго)", u"Congo, Republic of the..."),
    ("CH", u"Швейцарская Конфедерация", u"Switzerland"),
    ("CI", u"Кот-д'Ивуар (Республика Кот-д’Ивуар)", u"Côte d'Ivoire"),
    ("CL", u"Чили (Республика Чили)", u"Chile"),
    ("CM", u"Камерун (Республика Камерун)", u"Cameroon"),
    ("CN", u"Китай (Китайская Народная Республика)", u"China"),
    ("CO", u"Колумбия (Республика Колумбия)", u"Colombia"),
    ("CR", u"Коста-Рика (Республика Коста-Рика)", u"Costa Rica"),
    ("CU", u"Куба (Республика Куба)", u"Cuba"),
    ("CV", u"Кабо-Верде (Республика Кабо-Верде)", u"Cape Verde"),
    ("CY", u"Кипр (Респу́блика Кипр)", u"Cyprus"),
    ("CZ", u"Чехия (Чешская Республика)", u"Czech Republic"),
    ("DE", u"Германия (Федеративная Республика Германия)", u"Germany"),
    ("DJ", u"Джибути (Республика Джибути)", u"Djibouti"),
    ("DK", u"Дания (Королевство Дания)", u"Kingdom of Denmark"),
    ("DM", u"Доминика (Содружество Доминики)", u"Dominica"),
    ("DO", u"Доминиканская Республика", u"Dominican Republic"),
    ("DZ", u"Алжир (Алжирская Народная Демократическая Республика)", u"Algeria"),
    ("EC", u"Эквадор (Республика Эквадор)", u"Ecuador"),
    ("EE", u"Эстония (Эстонская Республика)", u"Estonia"),
    ("EG", u"Египет (Арабская Республика Египет)", u"Egypt"),
    ("ER", u"Эритрея (Государство Эритрея)", u"Eritrea"),
    ("ES", u"Испания (Королевство Испания)", u"Spain"),
    ("ET", u"Эфиопия (Федеративная Демократическая Республика Эфиопия)", u"Ethiopia"),
    ("FI", u"Финляндия (Финляндская Республика)", u"Finland"),
    ("FJ", u"Фиджи (Республика Островов Фиджи)", u"Fiji"),
    ("FM", u"Микронезия (Федеративные Штаты Микронезия)", u"Micronesia, Federated States of..."),
    ("FR", u"Франция (Французская Республика)", u"France"),
    ("GA", u"Габон (Габонская Республика)", u"Gabon"),
    ("GD", u"Гренада", u"Grenada"),
    ("GE", u"Грузия", u"Georgia"),
    ("GH", u"Гана (Республика Гана)", u"Ghana"),
    ("GM", u"Гамбия (Республика Гамбия)", u"Gambia"),
    ("GN", u"Гвинея (Гвинейская Республика)", u"Guinea"),
    ("GQ", u"Экваториальная Гвинея (Республика Экваториальная Гвинея)", u"Equatorial Guinea"),
    ("GR", u"Греция (Греческая Республика)", u"Greece"),
    ("GT", u"Гватемала (Республика Гватемала)", u"Guatemala"),
    ("GW", u"Гвинея-Бисау (Республика Гвинея-Бисау)", u"Guinea-Bissau"),
    ("GY", u"Гайана (Кооперативная Республика Гайана)", u"Guyana"),
    ("HN", u"Гондурас (Республика Гондурас)", u"Honduras"),
    ("HR", u"Хорватия (Республика Хорватия)", u"Croatia"),
    ("HT", u"Гаити (Республика Гаити)", u"Haiti"),
    ("HU", u"Венгрия (Венгерская Республика)", u"Hungary"),
    ("ID", u"Индонезия (Республика Индонезия)", u"Indonesia"),
    ("IE", u"Ирландия", u"None"),
    ("IL", u"Израиль (Государство Израиль)", u"Israel"),
    ("IN", u"Индия (Республика Индия)", u"India"),
    ("IQ", u"Ирак (Республика Ирак)", u"None"),
    ("IR", u"Иран (Исламская Республика Иран)", u"None"),
    ("IS", u"Исландия", u"Iceland"),
    ("IT", u"Италия (Итальянская Республика)", u"Italy (Italian Republic)"),
    ("JM", u"Ямайка", u"Jamaica"),
    ("JO", u"Иордания (Иорданское Хашимитское Королевство)", u"Jordan"),
    ("JP", u"Япония", u"Japan"),
    ("KE", u"Кения", u"Kenya"),
    ("KG", u"Киргизия (Киргизская Республика)", u"Kyrgyzstan"),
    ("KH", u"Камбоджа (Королевство Камбоджа)", u"Cambodia"),
    ("KI", u"Кирибати (Республика Кирибати)", u"Kiribati"),
    ("KM", u"Коморские Острова (Союз Коморских Островов)", u"Comoros"),
    ("KN", u"Сент-Китс и Невис (Федерация Сент-Китс и Невис)", u"Saint Kitts and Nevis"),
    ("KP", u"Корейская Народно-Демократическая Республика", u"Democratic People's Republic of Korea"),
    ("KR", u"Республика Корея", u"Republic of Korea"),
    ("KW", u"Кувейт (Государство Кувейт)", u"Kuwait"),
    ("KZ", u"Казахстан (Республика Казахстан)", u"Kazakhstan"),
    ("LA", u"Лаос (Лаосская Народно-Демократическая Республика)", u"Lao People's Democratic Republic"),
    ("LB", u"Ливан (Ливанская Республика)", u"Lebanon"),
    ("LC", u"Сент-Люсия", u"Saint Lucia"),
    ("LI", u"Лихтенштейн (Княжество Лихтенштейн)", u"Liechtenstein"),
    ("LK", u"Шри-Ланка (Демократическая Социалистическая Республика Шри-Ланка)", u"Sri Lanka"),
    ("LR", u"Либерия (Республика Либерия)", u"Liberia"),
    ("LS", u"Лесото (Королевство Лесото)", u"Lesotho"),
    ("LT", u"Литва (Литовская Республика)", u"Lithuania"),
    ("LU", u"Люксембург (Великое Герцогство Люксембург)", u"Luxembourg"),
    ("LV", u"Латвия (Латвийская Республика)", u"Latvia"),
    ("LY", u"Ливия (Великая Социалистическая Народная Ливийская Арабская Джамахирия)", u"Libyan Arab Jamahiriya"),
    ("MA", u"Марокко (Королевство Марокко)", u"Morocco"),
    ("MC", u"Монако (Княжеством Монако)", u"Monaco"),
    ("MD", u"Молдова (Республика Молдова)", u"Moldova"),
    ("ME", u"Черногория (Республика Черногория)", u"Montenegro"),
    ("MG", u"Мадагаскар (Республика Мадагаскар)", u"Madagascar"),
    ("MH", u"Маршалловы Острова (Республика Маршалловы Острова)", u"Marshall Islands"),
    ("MK", u"Македония (Республика Македония)", u"Macedonia"),
    ("ML", u"Мали (Республика Мали)", u"Mali"),
    ("MM", u"Мьянма (Союз Мьянма)", u"Myanmar"),
    ("MN", u"Монголия", u"Mongolia"),
    ("MR", u"Мавритания (Исламская Республика Мавритания)", u"Mauritania"),
    ("MT", u"Мальта (Республика Мальта)", u"Malta"),
    ("MU", u"Маврикий (Республика Маврикий)", u"Mauritius"),
    ("MV", u"Мальдивские Острова", u"Maldives"),
    ("MW", u"Малави (Республика Малави)", u"Malawi"),
    ("MX", u"Мексика (Мексиканские Соединенные Штаты)", u"Mexico"),
    ("MY", u"Малайзия", u"Malaysia"),
    ("MZ", u"Мозамбик (Республика Мозамбик)", u"Mozambique"),
    ("NA", u"Намибия (Республика Намибия)", u"Namibia"),
    ("NE", u"Нигер (Республика Нигер)", u"Niger"),
    ("NG", u"Нигерия (Федеративная Республика Нигерия)", u"Nigeria"),
    ("NI", u"Никарагуа (Республика Никарагуа)", u"Nicaragua"),
    ("NL", u"Нидерланды (Королевство Нидерландов)", u"Netherlands"),
    ("NO", u"Норвегия (Королевство Норвегия)", u"Norway"),
    ("NP", u"Непал", u"Nepal"),
    ("NR", u"Науру (Республика Науру)", u"Nauru"),
    ("NZ", u"Новая Зеландия", u"New Zealand"),
    ("OM", u"Оман (Султанат Оман)", u"Oman"),
    ("PA", u"Панама (Республика Панама)", u"Panama"),
    ("PE", u"Перу (Республика Перу)", u"Peru"),
    ("PG", u"Папуа-Новая Гвинея (Независимое Государство Папуа-Новая Гвинея)", u"Papua New Guinea"),
    ("PH", u"Филиппины (Республика Филиппины)", u"Philippines"),
    ("PK", u"Пакистан (Исламская Республика Пакистан)", u"Pakistan"),
    ("PL", u"Польша (Республика Польша)", u"Poland"),
    ("PS", u"Палестинская национальная администрация (ПНА)", u"Palestinian National Authority"),
    ("PT", u"Португалия (Португальская Республика)", u"Portugal"),
    ("PW", u"Палау (Республика Палау)", u"Palau"),
    ("PY", u"Парагвай (Республика Парагвай)", u"Paraguay"),
    ("QA", u"Катар (Государство Катар)", u"Qatar"),
    ("RO", u"Румыния", u"Romania"),
    ("RS", u"Сербия (Республика Сербия)", u"Serbia (Republic of Serbia)"),
    ("RU", u"Россия (Российская Федерация)", u"Russian Federation"),
    ("RW", u"Руанда (Республика Руанда)", u"Rwanda"),
    ("SA", u"Саудовская Аравия (Королевство Саудовская Аравия)", u"Saudi Arabia"),
    ("SB", u"Соломоновы Острова", u"Solomon Islands"),
    ("SC", u"Сейшельские Острова (Республика Сейшельские Острова)", u"Seychelles"),
    ("SD", u"Судан (Республика Судан)", u"Sudan"),
    ("SE", u"Швеция (Королевство Швеция)", u"Sweden"),
    ("SG", u"Сингапур", u"Singapore"),
    ("SI", u"Словения (Республика Словения)", u"Slovenia"),
    ("SK", u"Словакия (Республика Словакия)", u"Slovakia"),
    ("SL", u"Сьерра-Леоне (Республика Сьерра-Леоне)", u"Sierra Leone"),
    ("SM", u"Сан-Марино (Республика Сан-Марино)", u"San Marino"),
    ("SN", u"Сенегал (Республика Сенегал)", u"Senegal"),
    ("SO", u"Сомали (Сомалийская Демократическая Республика)", u"Somalia"),
    ("SR", u"Суринам (Республика Суринам)", u"Suriname"),
    ("ST", u"Сан-Томе и Принсипи (Демократическая Республика Сан-Томе и Принсипи)", u"Sao Tome and Principe"),
    ("SV", u"Сальвадор (Республика Эль-Сальвадор)", u"El Salvador"),
    ("SY", u"Сирийская Арабская Республика", u"Syrian Arab Republic"),
    ("SZ", u"Свазиленд (Королевство Свазиленд)", u"Swaziland"),
    ("TD", u"Чад (Республика Чад)", u"Chad"),
    ("TG", u"Того (Тоголезская Республика)", u"Togo"),
    ("TH", u"Таиланд (Королевство Таиланд)", u"Thailand"),
    ("TJ", u"Таджикистан (Республика Таджикистан)", u"Tajikistan"),
    ("TL", u"Тимор-Лешти (Демократическая Республика Восточный Тимор)", u"Timor-Leste"),
    ("TM", u"Туркменистан", u"Turkmenistan"),
    ("TN", u"Тунис (Тунисская Республика)", u"Tunisia"),
    ("TO", u"Тонга (Королевство Тонга)", u"Tonga"),
    ("TR", u"Турция (Турецкая республика)", u"Turkey (The Turkish Republic)"),
    ("TT", u"Тринидад и Тобаго (Республика Тринидад и Тобаго)", u"Trinidad and Tobago"),
    ("TV", u"Тувалу", u"Tuvalu"),
    ("TZ", u"Танзания (Объединенная Республика Танзания)", u"United Republic of Tanzania (14 December 1961)"),
    ("UA", u"Украина", u"Ukraine"),
    ("UG", u"Уганда (Республика Уганда)", u"Uganda"),
    ("US", u"Соединенные Штаты Америки", u"United States of America"),
    ("UY", u"Уругвай (Восточная Республика Уругвай)", u"Uruguay"),
    ("UZ", u"Узбекистан (Республика Узбекистан)", u"Uzbekistan"),
    ("VA", u"Город-государство Ватикан", u"Vatikan City"),
    ("VC", u"Сент-Винсент и Гренадины", u"Saint Vincent and the Grenadines"),
    ("VE", u"Венесуэла (Боливарианская Республика Венесуэла)", u"The Bolivarian Republic of Venezuela"),
    ("VN", u"Вьетнам (Социалистическая Республика Вьетнам)", u"Viet Nam"),
    ("VU", u"Вануату (Республика Вануату)", u"Vanuatu"),
    ("WS", u"Самоа (Независимое государство Самоа)", u"Samoa"),
    ("XA", u"Абхазия (Республика Абхазия)", u"Abkhazia (the Republic of Abkhazia)"),
    ("XO", u"Южная Осетия", u"South Ossetia (the Republic of South Ossetia)"),
    ("YE", u"Йемен (Йеменская Республика)", u"Yemen"),
    ("ZA", u"Южно-Африканская Республика (ЮАР)", u"South Africa"),
    ("ZM", u"Замбия (Республика Замбия)", u"Zambia"),
    ("ZW", u"Зимбабве (Республика Зимбабве)", u"Zimbabwe"),
)
